linters:
  enable-all: true
  disable:
    - goconst
    - asasalint
    - nosnakecase
    - thelper
    - stylecheck
    - revive
    - golint
    - ireturn
    - dupl
    - gocyclo
    - gomoddirectives
    - forbidigo
    - maintidx
    - gocognit
    - forcetypeassert
    - execinquery
    - testpackage
    - prealloc
    - wrapcheck
    - varnamelen
    - tagliatelle
    - paralleltest
    - nonamedreturns
    - nlreturn
    - gomnd
    - goerr113
    - gochecknoglobals
    - gci
    - exhaustruct
    - exhaustivestruct
    - wsl
    - lll
    - godot
    - funlen
    - gochecknoinits
    - cyclop
    - nestif
